# access to IPES
# 2019-08
# from Erika
# may need 32-bit R to query Access database directly

# load library
library(RODBC) # database connection

#*** change this to your local IPES database within working directory
# assumes you are working in an R project
db <- here::here("data", "highSeas", "IPES_TrawlDB_v19.07f_2017_18_19.mdb") 

# access IPES database
myconn <- odbcConnectAccess2007(db)

# get all event data from bridge table
# get bridge data from IPES
bridge_orig <- sqlQuery(myconn, "SELECT BRIDGE_LOG.EVENT_DATE, BRIDGE_LOG.EVENT_NUMBER, BRIDGE_LOG.EVENT_TYPE, Year([EVENT_DATE]) AS [Year], BRIDGE_LOG.STRATUM, BRIDGE_LOG.BLOCK_DESIGNATION, Format([END_DEPLOYMENT_TIME],'Short Time') AS [Time], BRIDGE_LOG.TOW_DURATION, BRIDGE_LOG.START_LATITUDE, BRIDGE_LOG.START_LONGITUDE, BRIDGE_LOG.END_LATITUDE, BRIDGE_LOG.END_LONGITUDE, 1.852*[DISTANCE_TRAVELLED] AS DistanceKM, BRIDGE_LOG.BEARING, 1.852*[SPEED] AS [SpeedKM/hr], BRIDGE_LOG.SWELL_HEIGHT, BRIDGE_LOG.SEA_STATE_ID, BRIDGE_LOG.CLOUD_COVER, BRIDGE_LOG.START_BOTTOM_DEPTH, BRIDGE_LOG.MOUTH_OPENING_HEIGHT, BRIDGE_LOG.DOOR_SPREAD, BRIDGE_LOG.TARGET_HEADLINE_HEIGHT, IIf([USABILITY_CODE]=1,'Yes','No') AS Usable, IIf(DatePart('h',BRIDGE_LOG.END_DEPLOYMENT_TIME)>=21 Or DatePart('h', BRIDGE_LOG.END_DEPLOYMENT_TIME)<6,'Night','Day') AS DayNight
FROM BRIDGE_LOG
GROUP BY BRIDGE_LOG.EVENT_DATE, BRIDGE_LOG.EVENT_NUMBER, BRIDGE_LOG.EVENT_TYPE, Year([EVENT_DATE]), BRIDGE_LOG.STRATUM, BRIDGE_LOG.BLOCK_DESIGNATION, Format([END_DEPLOYMENT_TIME],'Short Time'), BRIDGE_LOG.TOW_DURATION, BRIDGE_LOG.START_LATITUDE, BRIDGE_LOG.START_LONGITUDE, BRIDGE_LOG.END_LATITUDE, BRIDGE_LOG.END_LONGITUDE, 1.852*[DISTANCE_TRAVELLED], BRIDGE_LOG.BEARING, 1.852*[SPEED], BRIDGE_LOG.SWELL_HEIGHT, BRIDGE_LOG.SEA_STATE_ID, BRIDGE_LOG.CLOUD_COVER, BRIDGE_LOG.START_BOTTOM_DEPTH, BRIDGE_LOG.MOUTH_OPENING_HEIGHT, BRIDGE_LOG.DOOR_SPREAD, BRIDGE_LOG.TARGET_HEADLINE_HEIGHT, IIf([USABILITY_CODE]=1,'Yes','No'), BRIDGE_LOG.TOW_NUMBER, IIf(DatePart('h',BRIDGE_LOG.END_DEPLOYMENT_TIME)>=21 Or DatePart('h', BRIDGE_LOG.END_DEPLOYMENT_TIME)<6,'Night','Day')
HAVING (((BRIDGE_LOG.BLOCK_DESIGNATION)>0))
ORDER BY BRIDGE_LOG.EVENT_DATE, BRIDGE_LOG.EVENT_NUMBER;")

# get species data from IPES
species_orig <- sqlQuery(myconn, "SELECT SPECIES.SPECIES_CODE, SPECIES.COMMON_NAME, SPECIES.SCIENTIFIC_NAME, CATCH.CATCH_WEIGHT, BRIDGE_LOG.USABILITY_CODE
FROM TRIP LEFT JOIN (BRIDGE_LOG LEFT JOIN (SPECIES RIGHT JOIN CATCH ON SPECIES.SPECIES_CODE = CATCH.SPECIES_CODE) ON BRIDGE_LOG.BRIDGE_LOG_ID = CATCH.BRIDGE_LOG_ID) ON TRIP.TRIP_ID = BRIDGE_LOG.TRIP_ID
WHERE (BRIDGE_LOG.USABILITY_CODE=1 AND BRIDGE_LOG.BLOCK_DESIGNATION>0);")

# get data for catch table
# remove tows outside of IPES ie negative block numbers
catch_orig <- sqlQuery(myconn, "SELECT CATCH.SPECIES_CODE, SPECIES.SCIENTIFIC_NAME, SPECIES.COMMON_NAME, CATCH.CATCH_WEIGHT, BRIDGE_LOG.EVENT_NUMBER, BRIDGE_LOG.BLOCK_DESIGNATION, BRIDGE_LOG.USABILITY_CODE
FROM SPECIES RIGHT JOIN (TRIP LEFT JOIN (BRIDGE_LOG LEFT JOIN CATCH ON BRIDGE_LOG.BRIDGE_LOG_ID = CATCH.BRIDGE_LOG_ID) ON TRIP.TRIP_ID = BRIDGE_LOG.TRIP_ID) ON SPECIES.SPECIES_CODE = CATCH.SPECIES_CODE
WHERE (((BRIDGE_LOG.EVENT_TYPE)='midwater tow') AND ((BRIDGE_LOG.BLOCK_DESIGNATION)>0));")

# close connection to IPES database
close(myconn)

