## Clean and merge data from IPES and High Seas Access databases
# Note: 32-bit R needs to be used to import data from Access

library(RODBC); library(tidyverse); library(ggplot2)

# Access databases saved locally to work computer to import bridge (i.e. total
# catches) and genetics data from historical (high seas) and contemporary (IPES)
# databases
pathHighSeas <- here::here("data", "highSeas", "HSSALMON.accdb")
conHS <- odbcConnectAccess2007(pathHighSeas)

# High seas bridge data - includes catch totals
bridgeQry <- "SELECT BRIDGE.STATION_ID, BRIDGE.EVENT, BRIDGE.STATION, 
                     BRIDGE.YEAR, BRIDGE.MONTH, BRIDGE.DAY, BRIDGE.DATE, 
                     BRIDGE.JULIAN_DATE, BRIDGE.START_TIME, BRIDGE.START_LAT, 
                     BRIDGE.START_LONG, BRIDGE.END_LAT, BRIDGE.END_LONG, 
                     BRIDGE.DISTANCE, BRIDGE.DUR, BRIDGE.[SOG-KTS], 
                     BRIDGE.HEADING, BRIDGE.START_BOT_DEPTH, 
                     BRIDGE.END_BOT_DEPTH, BRIDGE.NET_OPENING_WIDTH, 
                     BRIDGE.NET_OPENING_HEIGHT, BRIDGE.HEAD_DEPTH, 
                     BRIDGE.CK, BRIDGE.CK_JUV, BRIDGE.CK_ADULT, 
                     BRIDGE.GEAR_TYPE, BRIDGE.COMMENTS
              FROM BRIDGE;"
bridgeHS <- sqlQuery(conHS, bridgeQry) 

# High seas Chinook GSI data
chinDNAQry <- "SELECT BIOLOGICAL.FISH_NUMBER, STATION_INFO.REGION, BRIDGE.Year, 
  BRIDGE.Month, BRIDGE.Day, BRIDGE.START_LAT, BRIDGE.START_LONG, 
  BIOLOGICAL.SPECIES, BIOLOGICAL.SHIP_FL, BIOLOGICAL.SHIP_TL, BIOLOGICAL.SHIP_WT, 
  DNA_CHINOOK_STOCK_ID.[BATCH-DNA_NUMBER], DNA_CHINOOK_STOCK_ID.STOCK_1, 
  DNA_CHINOOK_STOCK_ID.STOCK_2, DNA_CHINOOK_STOCK_ID.STOCK_3, 
  DNA_CHINOOK_STOCK_ID.STOCK_4, DNA_CHINOOK_STOCK_ID.STOCK_5, 
  DNA_CHINOOK_STOCK_ID.REGION_1, DNA_CHINOOK_STOCK_ID.REGION_2,
  DNA_CHINOOK_STOCK_ID.REGION_3, DNA_CHINOOK_STOCK_ID.REGION_4, 
  DNA_CHINOOK_STOCK_ID.REGION_5, DNA_CHINOOK_STOCK_ID.PROB_1, 
  DNA_CHINOOK_STOCK_ID.PROB_2, DNA_CHINOOK_STOCK_ID.PROB_3, 
  DNA_CHINOOK_STOCK_ID.PROB_4, DNA_CHINOOK_STOCK_ID.PROB_5
  FROM STATION_INFO 
INNER JOIN ((BRIDGE INNER JOIN BIOLOGICAL_JUNCTION ON BRIDGE.STATION_ID = 
  BIOLOGICAL_JUNCTION.STATION_ID) INNER JOIN (BIOLOGICAL INNER JOIN 
  DNA_CHINOOK_STOCK_ID ON BIOLOGICAL.FISH_NUMBER = 
  DNA_CHINOOK_STOCK_ID.FISH_NUMBER) ON (BIOLOGICAL_JUNCTION.FISH_NUMBER = 
  DNA_CHINOOK_STOCK_ID.FISH_NUMBER) AND (BIOLOGICAL_JUNCTION.FISH_NUMBER = 
  BIOLOGICAL.FISH_NUMBER)) ON (STATION_INFO.STATION_ID = BRIDGE.STATION_ID) AND 
  (STATION_INFO.STATION_ID = BIOLOGICAL_JUNCTION.STATION_ID)
WHERE (((BIOLOGICAL.SPECIES)='chinook'));
"
chinHS <- sqlQuery(conHS, chinDNAQry) %>% 
  glimpse()

# IPES bridge data (no catch)
bridgeIPESQuery <- "SELECT BRIDGE_LOG.BRIDGE_LOG_ID,
  BRIDGE_LOG.BRIDGE_LOG_FIELD_ID, BRIDGE_LOG.TRIP_ID, 
  BRIDGE_LOG.EVENT_DATE, BRIDGE_LOG.EVENT_NUMBER, BRIDGE_LOG.TOW_NUMBER, 
  BRIDGE_LOG.EVENT_TYPE, BRIDGE_LOG.EVENT_SUB_TYPE, BRIDGE_LOG.GEAR_CODE, 
  BRIDGE_LOG.BEGIN_DEPLOYMENT_TIME, BRIDGE_LOG.END_DEPLOYMENT_TIME, 
  BRIDGE_LOG.BEGIN_RETRIEVAL_TIME, BRIDGE_LOG.END_RETRIEVAL_TIME, 
  BRIDGE_LOG.BEGIN_FISH_SCHOOL_TIME, BRIDGE_LOG.TOW_DURATION, 
  BRIDGE_LOG.START_LATITUDE, BRIDGE_LOG.START_LONGITUDE, 
  BRIDGE_LOG.END_LATITUDE, BRIDGE_LOG.END_LONGITUDE, 
  BRIDGE_LOG.START_BOTTOM_DEPTH, BRIDGE_LOG.END_BOTTOM_DEPTH, 
  BRIDGE_LOG.AVG_BOTTOM_DEPTH, BRIDGE_LOG.START_GEAR_DEPTH, 
  BRIDGE_LOG.AVG_GEAR_DEPTH, BRIDGE_LOG.AVG_TOW_DEPTH, BRIDGE_LOG.TARGET_HEIGHT,
  BRIDGE_LOG.DISTANCE_TRAVELLED, BRIDGE_LOG.BEARING, 
  BRIDGE_LOG.WATER_TEMPERATURE, BRIDGE_LOG.USABILITY_CODE, BRIDGE_LOG.COMMENTS
FROM BRIDGE_LOG;
"
